### PR TITLE
Pass TestCase name to lists from stdout

### PR DESCRIPTION
**Pull request by casz**
Would like for TestResults to also return the lists of Passed, Failed, Skipped. So you can relay information in builds.

### CODE REVIEW

**Comment by casz** [comment]
@ghuntley anyhow I can help this along?

**Comment by ghuntley** [comment]
Howdy Joseph (@casz) do you want to help of maintenance of this Cake addin as a maintainer?

**Comment by casz** [comment]
@ghuntley Sorry I didn't get back to you.
I would like to help with maintenance 👍

**Comment by gep13** [comment]
@ghuntley if you want me to, I can get @casz added to the Organisation, with access to AppVeyor, etc.

**Comment by ghuntley** [comment]
@gep13 make it so. 

@casz welcome board. You are now the project lead; if you need insights or help then please let me know.

**Comment by gep13** [comment]
@casz I have just sent an invite for you to join the Cake-Contrib Organisation on GitHub.  I will also kick off a synchronisation process to add permissions to both GitHub and AppVeyor so that you will have all the necessary access.

If you can let me know the best email address to get you on, I can send you an invite to a Slack Team, and if you are on Twitter I will follow you from the Cake-Contrib Twitter account.

You can also reach out for information here: https://gitter.im/cake-contrib/Lobby

Please let me know if you have any questions.  Thank you very much for your help in maintaining this addin.

**Comment by ghuntley** [comment]
@gep13 https://emailaddress.github.io/?user=casz

**Comment by gep13** [comment]
@ghuntley yip, that is the same one that he DM'ed me through on Gitter 😄

**Comment by casz** [comment]
@ghuntley So what's the release process? I still have a few things I want to fix before release 👍

**Pull request merged**
